name: AI Code Review

on:
  pull_request:
    types: [opened, synchronize]

jobs:
  ai-review:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Get PR Diff
        id: get-diff
        uses: actions/github-script@v7
        with:
          script: |
            const prNumber = context.payload.pull_request.number;
            const diffResponse = await github.request("GET /repos/{owner}/{repo}/pulls/{pull_number}", {
              owner: context.repo.owner,
              repo: context.repo.repo,
              pull_number: prNumber,
              headers: { accept: "application/vnd.github.v3.diff" }
            });
            return diffResponse.data;
          result-encoding: string

      - name: AI Code Review
        id: ai-review
        env:
          OPENAI_API_KEY: ${{ secrets.OPENAI_API_KEY }}
        run: |
          DIFF="${{ steps.get-diff.outputs.result }}"

          RESPONSE=$(curl -s https://api.openai.com/v1/chat/completions \
            -H "Authorization: Bearer $OPENAI_API_KEY" \
            -H "Content-Type: application/json" \
            -d "{
              \"model\": \"gpt-4o-mini\",
              \"messages\": [
                {\"role\": \"system\", \"content\": \"You are a senior software engineer. Review this PR diff for bugs, security issues, performance improvements, and readability suggestions.\"},
                {\"role\": \"user\", \"content\": \"$DIFF\"}
              ]
            }" | jq -r '.choices[0].message.content')

          echo "response<<EOF" >> $GITHUB_OUTPUT
          echo "$RESPONSE" >> $GITHUB_OUTPUT
          echo "EOF" >> $GITHUB_OUTPUT

      - name: Post AI Review as PR Comment
        uses: marocchino/sticky-pull-request-comment@v2
        with:
          message: |
            🤖 **AI Code Review Suggestions**
            ${{ steps.ai-review.outputs.response }}
